### ISSUE TITLE
Down arrow in video view should be "Back" button

### ISSUE THREAD

**Issue by hadess** [Ippytraxx/gnome-twitch#10]
It should be a back button, similar to the one in GNOME Videos (totem), or gnome-photos.

**Comment by jangernert** [comment]
Agreed.
Also I would suggest to change the animation of the gtk.stack to SLIDE_RIGHT/SLIDE_LEFT instead of up/down as well :)

**Comment by Ippytraxx** [comment]
Yeah, this is the default GNOME behaviour. I just liked the up/down motion because the views (channels/favourites/games) use the left/right motion, so I wanted have something different. Alas it's no point going against the flow so I'll make it left/right and use the normal back button.

**Comment by hadess** [comment]
I think you'll need to reverse the direction of the animation when going back from a video, so that the video looks like it's on the right of the view (on right-to-left languages) and the opposite on left-to-right languages.

**Comment by Ippytraxx** [comment]
Ah right, that makes sense.
