### ISSUE TITLE
A long translation string for "Connecting to chat" gets cut off

### ISSUE THREAD

**Issue by dengelt** [Ippytraxx/gnome-twitch#107]
The first three characters of the string are cut off in this example, see screenshot below. Could the widget that is used allow automatic line breaks?

![bildschirmfoto von 2016-04-08 20-10-31](https://cloud.githubusercontent.com/assets/15182482/14393324/9f016134-fdc6-11e5-9f7d-3d444e860b24.png)

**Comment by dchristidis** [comment]
I think this can be fixed by adding a `max_width_chars` property to the label.

**Comment by Ippytraxx** [comment]
Yep, I only just briefly check the translations but this is an easy fix as @dchristidis pointed out.
