### ISSUE TITLE
Have to restart app to get chat to work after login

### ISSUE THREAD

**Issue by martinoj2009** [Ippytraxx/gnome-twitch#108]
This isn't a huge issue; however, after logging into the app with my Twitch account I had to restart the app to get the chat to work (show). Also, I shouldn't need to login just to see chat... although I don't know how that API works. When I use other Twitch apps I don't have to login to see the chat, it's public.

**Comment by Ippytraxx** [comment]
It should auto start chat after logging in also IRC requires that you authenticate using an OAuth token (https://github.com/justintv/Twitch-API/blob/master/IRC.md) so I don't know how these "other" Twitch apps show chat.

**Comment by dengelt** [comment]
This is not documented in their official documentation you linked, but you can just use a nickname like `justinfan2134634` without a password. I don't know what happens when two anonymous users log in with the same number though.

[Source](https://discuss.dev.twitch.tv/t/how-to-connect-to-irc-without-login-and-password-closed/269)

**Comment by Ippytraxx** [comment]
@dengelt Amazing stuff, thanks for finding this! This actually annoyed me quite a bit after trying to make everything available to people without accounts, chat required one.

@martinoj2009 So it looks like I can implement chat without logging in albeit you can't send any messages or anything.

**Comment by dengelt** [comment]
It seems like two users can log in with the same number without any problems. Also very big numbers still work, like even beyond 2^64.

**Comment by dchristidis** [comment]
Great work @dengelt. Not being able to see the chat without an account has been an unfortunate limitation.

**Comment by Ippytraxx** [comment]
@martinoj2009 So I just tried GT on a fresh VM with Ubuntu Mate 15.10 and it started chat just fine. I read the WebUpd8 article (http://www.webupd8.org/2016/04/gnome-twitch-020-adds-chat-feature.html) and it seems like other people have this issue.

What happened when you tried logging in and opening a stream? Did it show the "Not logged into Twitch" view?

**Comment by martinoj2009** [comment]
Thanks for looking into it Lppytraxx. I don't recall if the GM showed "Not logged into Twitch." I will remove the application and the application files in ~/.local/share/gnome-twitch and try again to see what happens.

**Comment by martinoj2009** [comment]
I didn't see this happen after reinstalling and removing the files. This time after logging in I was able to go right into chat. I'll try a VM of Fedora 23. Troubleshooting this stuff is so weird lol.

**Comment by martinoj2009** [comment]
I'm sorry @Ippytraxx I made a VM and wasn't able to recreate the issue again. It again allowed me to login and access the chat right away. I'm not sure if I logged in a certain way.

**Comment by Ippytraxx** [comment]
Inactive now so closing, please re-open if anyone is still experiencing this.
