### ISSUE TITLE
[Feature] PPA for Ubuntu

### ISSUE THREAD

**Issue by Sunderland93** [Ippytraxx/gnome-twitch#114]
I create PPA for GNOME Twitch https://launchpad.net/~samoilov-lex/+archive/ubuntu/gnome-twitch

Currently support Ubuntu 16.04 Xenial Xerus

**Comment by Ippytraxx** [comment]
I see you're using source from the PPA I created. I just want to let you know that I have literally 0 knowledge created PPAs and that source is pure black magic that I randomly threw together :P . Maybe for future releases you might want to look at @dengelt Debian packages and modify them.

**Comment by dengelt** [comment]
Today the 0.2.0 version of my Debian package got accepted in unstable. It has a few improvements over the previous packaging, for example hardening and only linking needed libraries, which could be useful for your PPA too @Sunderland93 .

**Comment by Sunderland93** [comment]
@dengelt thanks
