### ISSUE TITLE
Gnome Twitch fails to work with libva-intel-driver

### ISSUE THREAD

**Issue by frantisekz** [Ippytraxx/gnome-twitch#116]
Gnome Twitch outputs only black screen instead of video when libva-intel-driver is installed on system.
On the other hand, Gnome Totem (which I believe uses same backend to output video) works fine.

I've tried to recompile newer version of libva-intel-driver (1.7.0 instead of 1.6.2) but result is pretty much same.

Output from Gnome Twitch with libva-intel-driver:
```
[16:44:43] GNOME-Twitch - Message : "{GtApp} Loading chat settings"
[16:44:43] GNOME-Twitch - Message : "{GtApp} Activate"
[16:44:43] Gtk - Warning : "Theme parsing error: gnome-twitch-style.css:43:21: The '-gtk-image-effect' property has been renamed to '-gtk-icon-effect'"
[16:44:49] GNOME-Twitch - Message : "{GtPlayer} Opening stream 'dreamhackcs' with quality 'high'"
[16:44:49] Clutter - Critical : "clutter_actor_remove_child: assertion 'child->priv->parent == self' failed"
[16:44:49] Clutter - Critical : "clutter_actor_add_child: assertion 'child->priv->parent == NULL' failed"
libva info: VA-API version 0.39.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib64/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva info: va_openDriver() returns 0

(gnome-twitch:10480): GStreamer-CRITICAL **: gst_buffer_copy_with_flags: assertion 'buffer != NULL' failed
[16:44:50] Cogl - Warning : "driver/gl/cogl-framebuffer-gl.c:983: GL error (1280): Invalid enumeration value
```

Output from Totem with libva-intel-driver:
```
libva info: VA-API version 0.39.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib64/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva info: va_openDriver() returns 0
```

**Comment by dchristidis** [comment]
The same thing seems to happen to Epiphany. I think that this is a GStreamer issue, and thus cannot be addressed by GNOME Twitch.

```
Απρ 17 13:15:00 X1C epiphany.desktop[25056]: libva info: VA-API version 0.39.0
Απρ 17 13:15:00 X1C epiphany.desktop[25056]: libva info: va_getDriverName() returns 0
Απρ 17 13:15:00 X1C epiphany.desktop[25056]: libva info: Trying to open /usr/lib64/dri/i965_drv_video.so
Απρ 17 13:15:00 X1C epiphany.desktop[25056]: libva info: Found init function __vaDriverInit_0_37
Απρ 17 13:15:00 X1C epiphany.desktop[25056]: libva info: va_openDriver() returns 0
Απρ 17 13:15:00 X1C epiphany.desktop[25056]: (WebKitWebProcess:25073): GStreamer-CRITICAL **: gst_buffer_copy_with_flags: assertion 'buffer != NULL' failed
```

**Comment by frantisekz** [comment]
Epiphany works for me without any issues:
```
libva info: VA-API version 0.39.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib64/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva info: va_openDriver() returns 0
```

**Comment by Ippytraxx** [comment]
Are you using Optimus (Intel + NVidia hybrid graphics)? 

The problem might lie in Cogl (used by Clutter) which is doing the actual rendering. I'm not doing any weird setup or config so I'm not sure if this anything I can fix in GT.

However I am working on providing other backends, mainly GtkGst (in gst-plugins-bad though) and MPV to hopefully work around problems like this.

**Comment by frantisekz** [comment]
No, I have just Intel Graphics in my laptop.

So, should I open bug against Gstreamer in Gnome Bugzilla? The problem is that I am not sure, where to report bug. If issue isn't in Gnome Twitch, I think this can be caused by issue in gstreamer (probably gstreamer-vaapi), Cogl, or even in libva-intel-driver itself.

**Comment by dchristidis** [comment]
I was mistaken then, sorry for the misinformation.

**Comment by Ippytraxx** [comment]
Probably the GNOME Bugzilla is best under clutter-gst http://bugzilla.gnome.org/enter_bug.cgi?product=clutter-gst 

Thanks for taking your time if you do submit a bug report, unfortunately I can't replicate this problem so I wouldn't be able to provide any info.

**Comment by dengelt** [comment]
I just tested this and I can reproduce it on my Laptop (Intel GPU) and on my Desktop (Nvidia GPU, proprietary driver), so I'd say the problem is not in libva-intel-driver. This is the relevant part from my desktop:

```
[11:00:30] Clutter - Critical : "clutter_actor_remove_child: assertion 'child->priv->parent == self' failed"
[11:00:30] Clutter - Critical : "clutter_actor_add_child: assertion 'child->priv->parent == NULL' failed"
[11:00:30] Gtk - Warning : "gtk_widget_size_allocate(): attempt to allocate widget with width -13 and height 32"
[11:00:30] Gtk - Warning : "gtk_widget_size_allocate(): attempt to allocate widget with width -13 and height 20"
libva info: VA-API version 0.39.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/nvidia_drv_video.so
libva info: Found init function __vaDriverInit_0_37
libva info: va_openDriver() returns 0
[11:00:31] Cogl - Warning : "driver/gl/cogl-framebuffer-gl.c:983: GL error (1280): Invalid enumeration value
```

**Comment by frantisekz** [comment]
Bug reported to upstream: https://bugzilla.gnome.org/show_bug.cgi?id=765174

**Comment by frantisekz** [comment]
> Probably the GNOME Bugzilla is best under clutter-gst http://bugzilla.gnome.org/enter_bug.cgi?product=clutter-gst
> 
> Thanks for taking your time if you do submit a bug report, unfortunately I can't replicate this problem so I wouldn't be able to provide any info.

According to gstreamer developer, the bug is in gnome-twitch:

https://bugzilla.gnome.org/show_bug.cgi?id=765174

**Comment by Ippytraxx** [comment]
Right... this is interesting because practically the only interaction I have with clutter-gst in terms of video is:

    clutter_gst_playback_set_uri(priv->player, NULL);
    clutter_gst_player_set_playing(CLUTTER_GST_PLAYER(priv->player), FALSE);

Unfortunately I don't really know how to implement what they are saying without deep diving into the GStreamer pipeline which is overkill imo because I'm not fiddling with it in the first place.

What you can try is to change https://github.com/Ippytraxx/gnome-twitch/blob/master/src/gt-player-clutter.c#L744 and comment out the line with `GST_BUFFERING_MODE_DOWNLOAD` and uncomment `GST_BUFFERING_MODE_STREAM`. If you need help compiling/installing from source let me know (instructions are in the readme).

Otherwise the best solution I have is to wait until one of the other back ends are implemented.

**Comment by frantisekz** [comment]
Didn't help (no change at all). 
I've tried to downgrade gstreamer1-vaapi (screen is black with version 0.6.1 and app is crashing with 0.7.0).

I don't have any idea where can be the problem :/ It's weird that other apps using gst-vaapi work fine.

**Comment by Ippytraxx** [comment]
Ok so on my laptop (Intel HD4000 graphics), it works fine without `gstreamer-vaapi` and `libva-intel-driver` and with `gstreamer-vaapi 1.8.0` and `libva-intel-driver 1.7.0`. 

I just noticed that your gstreamer-vaapi version is extremely old?

Output from GT:
```
[20:10:26] GNOME-Twitch - Message : "{GtApp} Loading chat settings"
[20:10:26] GNOME-Twitch - Message : "{GtApp} Activate"
[20:10:31] GNOME-Twitch - Message : "{GtPlayer} Opening stream 'esl_csgo' with quality 'low'"
[20:10:31] Clutter - Critical : "clutter_actor_remove_child: assertion 'child->priv->parent == self' failed"
[20:10:31] Clutter - Critical : "clutter_actor_add_child: assertion 'child->priv->parent == NULL' failed"
[20:10:32] GNOME-Twitch - Message : "{GtIrc} Connecting"
[20:10:32] GNOME-Twitch - Message : "{GtIrc} Running chat worker thread for receive"
[20:10:32] GNOME-Twitch - Message : "{GtIrc} Joining channel '#esl_csgo'"
[20:10:32] GNOME-Twitch - Message : "{GtIrc} Running chat worker thread for send"
libva info: VA-API version 0.39.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva info: va_openDriver() returns 0
[20:10:45] GLib-GObject - Warning : "invalid cast from 'GtkBox' to 'GtWin'"
[20:10:45] GLib-GObject - Warning : "invalid cast from 'GtkBox' to 'GtWin'"
[20:10:45] GNOME-Twitch - Message : "{GtApp} Shutting down"
[20:10:45] GNOME-Twitch - Message : "{GtApp} Saving chat settings"

```

Output from `vainfo`:

```
libva info: VA-API version 0.39.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva info: va_openDriver() returns 0
vainfo: VA-API version: 0.39 (libva 1.7.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Haswell Mobile - 1.7.0
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264MultiviewHigh      :	VAEntrypointVLD
      VAProfileH264MultiviewHigh      :	VAEntrypointEncSlice
      VAProfileH264StereoHigh         :	VAEntrypointVLD
      VAProfileH264StereoHigh         :	VAEntrypointEncSlice
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileJPEGBaseline           :	VAEntrypointVLD
```

**Comment by frantisekz** [comment]
Thanks for trying this out. Yes, Fedora has ancient version and when I was upgrading to newer, I was looking to no longer maintained page at freedesktop.org

Anyway, I managed to compile rpm with gst-vaapi 1.8.1 and again:
intel_do_flush_locked failed: No such file or directory

Totem works even with 1.8.1. After a while of googling, this "intel_do_flush_locked" failed could be bug in kernel/x driver/mesa. Do you have any idea where it's best to try reporting?

**Comment by Ippytraxx** [comment]
Bug already on the Intel Bugzilla https://bugs.freedesktop.org/show_bug.cgi?id=71759. You can see further down that the issue relates to Cogl, GStreamer and Clutter so it's probably the same thing happening to GT. 

Seems however to be a Fedora issue, try running `gst-launch-1.0 filesrc location=some_file.mp4 ! decodebin ! cluttersink` and see if you get the same problem.

There's a patch at the bottom if you feel like patching your driver.

**Comment by frantisekz** [comment]
LIBGL_DRI3_DISABLE=1 worked out, thanks again!
