### ISSUE TITLE
Login is broken

### ISSUE THREAD

**Issue by einalex** [Ippytraxx/gnome-twitch#130]
Hi!
When I try to login I get a "Message Corrupt" message in the login window after some time of waiting
The last message on the console is:
GNOME-Twitch - Message : "{GtTwitchLoginDlg} Got username 'einalex' from form"

This happens both with version 0.2 and the current git HEAD.
If I can do something to find the error, tell me and I'll do it.

**Comment by Ippytraxx** [comment]
Does this happen consistently, have you been able to log in at all? From what I can see online this seems to be related to Webkit, so not sure how much I can fix it through GT.

**Comment by einalex** [comment]
It happens everytime I try it. I had no luck signing in so far.

**Comment by Ippytraxx** [comment]
If I have time I'll see if I can file a upstream bug at the GtkWebKit project, but it seems like a pretty rare error.

Just as a workaround you can do the following:

1. Go to https://api.twitch.tv/kraken/oauth2/authorize?response_type=token&client_id=afjnp6n4ufzott4atb3xpb8l5a31aav&redirect_uri=http://localhost&scope=chat_login+user_follows_edit in a browser that works.

2. When you get redirected after logging in you should get [http://localhost/#access_token=$OAUTH_TOKEN&scope=chat_login+user_follows_edit](http://localhost/#access_token=$OAUTH_TOKEN&scope=chat_login+user_follows_edit)

3. Copy $OAUTH_TOKEN, open dconf, browse to `/com/gnome-twitch/app` and paste it into the oauth-token key. Alternatively you can run `gsettings set com.gnome-twitch.app oauth-token "$OAUTH_TOKEN"`

**Comment by torpet** [comment]
I experienced the same problem. Funnily enough, the OAuth token was set correctly. It was the username field that was not set correctly (it was empty).

**Comment by Ippytraxx** [comment]
@torpet What you were experiencing should be fixed now in #140

**Comment by Ippytraxx** [comment]
Closing this for now as it seems very specific and out of GT's control anyways.
