### ISSUE TITLE
Favourited streams are sometimes falsly shown as online

### ISSUE THREAD

**Issue by mattiasb** [Ippytraxx/gnome-twitch#135]
With `gnome-twitch` 0.2.0 I sometimes experience that favourited streams are shown as online when they in fact are offline.

Here's my favourites list from a few minutes ago on 0.2.0 (note the four online streams):
![Streams gnome-twitch thinks are online](https://cloud.githubusercontent.com/assets/1341313/16093456/428e597e-333c-11e6-87a1-8ab690c6ab7b.png)

Here's my live favourites on twitch.tv (note how only `numotthenummy` is online of the four above):
![Actual live streams](https://cloud.githubusercontent.com/assets/1341313/16093460/4438e726-333c-11e6-8040-9d121e8393bf.png)

I know that the favourites are different between twitch.tv and gnome-twitch in 0.2.0 but the four that  shows as online above are favourites on twitch.tv as well. Also when I click on one of these four only the `numotthenummy`-stream starts.

**Comment by mattiasb** [comment]
Testing now with latest git...

**Comment by mattiasb** [comment]
This seems to work in latest git. Sorry for the noise.

**Comment by Ippytraxx** [comment]
I reckon what happened seeing as all those 3 channels were streaming some MTG event that when the event was over, they stopped streaming and GT hadn't refreshed (2 minute refresh timer). Also don't worry about posting too much ;) I'm happy to receive feedback and bug reports.

**Comment by Ippytraxx** [comment]
Actually it could have also been this: ![screenshot from 2016-06-16 19-05-01](https://cloud.githubusercontent.com/assets/1663668/16126210/73998afa-33f7-11e6-8d3c-d663e18864b1.png)

I've fixed this by adding a extra param to the HTTP request, plus I'll hopefully add an extra visual detail when a stream is just hosting a playlist, sometime in the future.
