### ISSUE TITLE
Chat never logs in

### ISSUE THREAD

**Issue by joaojotta** [Ippytraxx/gnome-twitch#140]
Everytime I use Gnome Twitch I log in successfully but the chat tab never gets to log in.
Refreshing login or closing and opening the application isn't working.

screenshot
http://fileserver.imagebucket.net/img/k7j2lzegr7ore77jjmovxfsa5zhfiinn6w734szuvi/Screenshot%20from%202016-08-02%2001-35-42.png

terminal activity
http://pastebin.com/fg5X921e

System: Arch
Desktop: Cinnamon

Hope someone finds a solution

THANKS!!

**Comment by qptain-Nemo** [comment]
Same here, Arch, Xfce.

**Comment by Ippytraxx** [comment]
Urgh I don't know what's changed but the submit-form signal doesn't fire anymore from WebKit, so GT never gets the username.

I have a solution in mind but it won't appear in 0.2.0 unless I do more patching...

In the meantime you can run:

    gsettings set com.gnome-twitch.app user-name $USERNAME

After you have "logged in" and then restart GT.

**Comment by joaojotta** [comment]
It actually worked!!!

**Comment by Ippytraxx** [comment]
@joaojotta Alright good to hear :smile:, I'll try get 0.3.0 out the door ASAP which will have the fix.

**Comment by joaojotta** [comment]
Amazing!!!
