### ISSUE TITLE
Stream cropped + artifacts 

### ISSUE THREAD

**Issue by jangernert** [Ippytraxx/gnome-twitch#19]
Compared to the website the stream in gnome-twitch is cropped a few pixels in the top and at the bottom + there are some funky color artifacts at the bottom :D Happens on all streams I tested not just esl_sc2 ;)

![screenshot from 2015-10-09 00-59-28](https://cloud.githubusercontent.com/assets/12012494/10382207/e6aabd26-6e21-11e5-9ac4-2db3099b6766.png)

**Comment by Ippytraxx** [comment]
Hmm, the cropping is from GStreamer trying to keep the aspect ratio. There are two ways of fixing it: 

* Force the window to be in the same aspect ratio as the video.
* Force GStreamer to always fill the window.

I don't like either of these and the second one would lead to some serious warping of the video. So I'll have to think about it.

As for the artifacts, I feel like this is a GStreamer/GPU problem, which I don't have much control over. Again I'll try to look into it.

**Comment by jangernert** [comment]
The video would have enough space to display the missing lines of the video in the top and the bottom. This even happens in full-screen-mode on my 16:10 monitor with a 16:9 stream. So no space issues there.

Regarding GPU: I use the radeonSI foss driver on fedora 23 (very recent kernel + mesa). But never had any problems with other gstreamer based video players. But only playing local video files. So no idea if twitch stream is different.

**Comment by Ippytraxx** [comment]
Oh, on a closer look I see what you mean. I also have a 16:10 monitor so I just thought it was just resizing the video, but you are actually missing a bit of the top and bottom (the artifacts).

If you have a couple minutes could you please do a bit of troubleshooting for me:

1. Run this [python script](https://gist.github.com/Ippytraxx/14bd1ea09c81311ad906) like this `python twitch_live_url.py esl_sc2`
2. Copy one of the urls
3. Run `gst-play-1.0 "insert_url"` and let me know if you get the same artifacts.

**Comment by jangernert** [comment]
Sure can do:
```
python twitch.py esl_sc2
#EXTM3U
#EXT-X-TWITCH-INFO:NODE="video44.fra01",MANIFEST-NODE="video44.fra01",SERVER-TIME="1444425880.67",USER-IP="95.90.219.173",CLUSTER="fra01",MANIFEST-CLUSTER="fra01"
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="chunked",NAME="Source",AUTOSELECT=YES,DEFAULT=YES
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=3659195,RESOLUTION=1280x720,VIDEO="chunked"
http://video44.fra01.hls.ttvnw.net/hls-5b8b94/esl_sc2_16889420672_322637064/chunked/py-index-live.m3u8?token=id=7565264058088834938,bid=16889420672,exp=1444512280,node=video44-1.fra01.hls.justin.tv,nname=video44.fra01,fmt=chunked&sig=a376e137e5f0c02ad9d9d1fea0ec4f0fe5329862
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="high",NAME="High",AUTOSELECT=YES,DEFAULT=YES
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1760000,RESOLUTION=1280x720,VIDEO="high"
http://video44.fra01.hls.ttvnw.net/hls-5b8b94/esl_sc2_16889420672_322637064/high/py-index-live.m3u8?token=id=7565264058088834938,bid=16889420672,exp=1444512280,node=video44-1.fra01.hls.justin.tv,nname=video44.fra01,fmt=high&sig=1556dce7e2c2c732cf6a93ea43d9b9a3fc6dd7a3
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="medium",NAME="Medium",AUTOSELECT=YES,DEFAULT=YES
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=928000,RESOLUTION=852x480,VIDEO="medium"
http://video44.fra01.hls.ttvnw.net/hls-5b8b94/esl_sc2_16889420672_322637064/medium/py-index-live.m3u8?token=id=7565264058088834938,bid=16889420672,exp=1444512280,node=video44-1.fra01.hls.justin.tv,nname=video44.fra01,fmt=medium&sig=668f288cb3ba46de7fa892f759f3c65545195e1a
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="low",NAME="Low",AUTOSELECT=YES,DEFAULT=YES
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=596000,RESOLUTION=640x360,VIDEO="low"
http://video44.fra01.hls.ttvnw.net/hls-5b8b94/esl_sc2_16889420672_322637064/low/py-index-live.m3u8?token=id=7565264058088834938,bid=16889420672,exp=1444512280,node=video44-1.fra01.hls.justin.tv,nname=video44.fra01,fmt=low&sig=399bf6209a4c150b58c4e8a93ccb8cd9577e9102
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="mobile",NAME="Mobile",AUTOSELECT=YES,DEFAULT=YES
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=164000,RESOLUTION=400x226,VIDEO="mobile"
http://video44.fra01.hls.ttvnw.net/hls-5b8b94/esl_sc2_16889420672_322637064/mobile/py-index-live.m3u8?token=id=7565264058088834938,bid=16889420672,exp=1444512280,node=video44-1.fra01.hls.justin.tv,nname=video44.fra01,fmt=mobile&sig=8198413e0f69bd9c44af963525e00fb2be226ccf
```

```
gst-play-1.0 http://video44.fra01.hls.ttvnw.net/hls-5b8b94/esl_sc2_16889420672_322637064/mobile/py-index-live.m3u8?token=id=7565264058088834938,bid=16889420672,exp=1444512280,node=video44-1.fra01.hls.justin.tv,nname=video44.fra01,fmt=mobile&sig=8198413e0f69bd9c44af963525e00fb2be226ccf
[1] 5039
```
gst-play-1.0 basically does nothing. Just a zombie process.
However if I pass a random local video file (tested 1080p version of big buck bunny) I also get the artifacts. But I can't say for sure if some pixels at the top and bottom are missing. I only noticed it on the star craft 2 match because of the text that was cut off.

I will google around a little if its because of my drivers or the gstreamer version (1.6.0) ...

**Comment by jangernert** [comment]
Filed a bug against gstreamer:
https://bugzilla.gnome.org/show_bug.cgi?id=756320

**Comment by Ippytraxx** [comment]
Make sure to put the url in quotes with gst-play.

**Comment by jangernert** [comment]
Ah okay, with quotes it works. But still the same problems.

**Comment by Ippytraxx** [comment]
Yeah, well definitely a problem with GStreamer then. Unfortunately that pretty much puts it outside of my control. The bug report you made is probably the best way to get the problem solved. I'll leave the issue open for now and please report back if you get it fixed.

**Comment by Ippytraxx** [comment]
Just out of curiosity do you get the same problems if you play one of the urls in mpv or vlc? I will be adding a MPV backend to solve problems like this so users can choose whether they want to use GStreamer or something like MPV to play the stream.

**Comment by jangernert** [comment]
Sadly there is no rpmfusion for fedora 23, yet. I only can play stuff with gstreamer because I installed the gstreamer-libav rpm from the rpmfusion rawhide repository.
So no vlc or mplayer, yet. But I will test it as soon as it is available.

**Comment by Ippytraxx** [comment]
Hey can you try out gnome-twitch from the develop branch? I've rewritten the player using Clutter instead of writing directly to the X window. If you're lucky the artifacts might disappear.

**Comment by jangernert** [comment]
I did a git pull to update the code then went to the build folder (with files from last compile) and run ninja-build install. Is that correct?
The artifacts are still there. I tested for the gstreamer people a few different videosinks. This only happens with autosink and xvimagesink not with ximagesink and glimagesink.

**Comment by Ippytraxx** [comment]
Did you clone from the `develop` branch? That's where the new stuff is.

**Comment by jangernert** [comment]
Oh, I somehow did not notice "develp branch" in your first reply.
The new code seems to fix both issues :) Thx
