### ISSUE TITLE
GLib-GIO-ERROR

### ISSUE THREAD

**Issue by Joseph65** [Ippytraxx/gnome-twitch#20]
when i run gnome-twitch in the terminal i get this error

(gnome-twitch:4932): GLib-GIO-ERROR **: Settings schema 'com.gnome-twitch.app' is not installed

Trace/breakpoint trap (core dumped)

**Comment by Ippytraxx** [comment]
Are you installing this manually? If you are then you need to do the post install (see README). But mainly you will need to run `glib-compile-schemas /usr/share/glib-2.0/schemas` as root so the settings get recompiled.

If you are not doing this manually then contact the package maintainer and make sure they are doing the above in the post install script.
