### ISSUE TITLE
rpm repo

### ISSUE THREAD

**Issue by hmsintrepide** [Ippytraxx/gnome-twitch#26]
You share 2 packages, one for Ubuntu, one for Arch. Can we have a rpm package for Fedora/OpenSuse ?

**Comment by Ippytraxx** [comment]
Yep, once I tag and release 0.0.1 (pretty soon) I will look into packaging it up properly for all major distros.

**Comment by hmsintrepide** [comment]
Thanks

**Comment by Ippytraxx** [comment]
@hmsintrepide I've created a [copr repo](https://copr.fedoraproject.org/coprs/ippytraxx/gnome-twitch/) that you can now use to install GNOME Twitch. It works for me in my Fedora 22 virtual machine, but could you please test the package and report back whether it works or not?
