### ISSUE TITLE
Thumbnails don't load

### ISSUE THREAD

**Issue by mrwhale** [Ippytraxx/gnome-twitch#27]
Hey @Ippytraxx awesome piece of software!
I installed the deb via http://www.getdeb.net/app/GNOME%20Twitch and it seems that the thumbnails don't load for me

![selection_020](https://cloud.githubusercontent.com/assets/7307429/10419117/f07167ee-70b8-11e5-9818-c7ecd338e27a.png)

Steams work perfect once I've selected one to watch, but navigating around is text only

I'm running Ubuntu 15.04 with Gnome 3.14
Here is the only output when running via terminal

![selection_021](https://cloud.githubusercontent.com/assets/7307429/10419118/f0747c5e-70b8-11e5-912c-4b01afdda038.png)

If its just me, then you can close and I will try build from source instead!

**Comment by Ippytraxx** [comment]
Thanks a lot!

You need at least GTK+ 3.16 installed and seeing as you are running GNOME 3.14, I don't think you have it. If you still have this problem with 3.16 you can reopen the issue.

**Comment by mrwhale** [comment]
Thanks! Such a rookie :P didn't properly read the dependencies. Just update to Gnome 3.16 but still no luck :(

`The GLib-GObject-warnings` aren't in terminal when I start the app anymore, just the first one still

**Comment by Ippytraxx** [comment]
Hmm it's weird that any errors aren't being thrown. Could you please try compiling from the latest source? Instructions are in the readme, however you don't need to run `ninja install`, it's enough to run `ninja` and then run `./src/gnome-twitch` from the build directory.

**Comment by Ippytraxx** [comment]
No reply.
