### ISSUE TITLE
[SOLVED] Video not working with hybird graphics

### ISSUE THREAD

**Issue by nashamri** [Ippytraxx/gnome-twitch#30]
Hello,

First of all, thanks for this really cool application :+1: 

The `master` branch is working fine with me but today I tried the `develop` branch and the video isn't working, yet I can hear the sound just fine.

This is the terminal output:

```
[14:52:42] (null) - Message : '{GtApp} Activate'
libva info: VA-API version 0.38.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_38
libva info: va_openDriver() returns 0

(gnome-twitch:1997): GStreamer-CRITICAL **: gst_buffer_copy_with_flags: assertion 'buffer != NULL' failed

(gnome-twitch:1997): GStreamer-CRITICAL **: gst_buffer_copy_with_flags: assertion 'buffer != NULL' failed
libva info: VA-API version 0.38.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_38
libva info: va_openDriver() returns 0

(gnome-twitch:1997): GStreamer-CRITICAL **: gst_buffer_copy_with_flags: assertion 'buffer != NULL' failed

(gnome-twitch:1997): GStreamer-CRITICAL **: gst_buffer_copy_with_flags: assertion 'buffer != NULL' failed
[14:52:50] Cogl - Warning : 'driver/gl/cogl-framebuffer-gl.c:157: GL error (1280): Invalid enumeration value
```

I'm running Arch and I have a hybird graphics setup (intel+bumblebee). I tested it on my other laptop which has intel graphics only and it's working fine.

**Comment by Ippytraxx** [comment]
Hmm another person had this problem (#21). What output do you get when running `vainfo`. This is inside GStreamer so I can't actually do so much in terms of changing code but I think that it's trying to load non-existant drivers for hardware acceleration.

**Comment by Ippytraxx** [comment]
Do you have [libva-intel-driver](https://www.archlinux.org/packages/extra/x86_64/libva-intel-driver/) installed?

**Comment by nashamri** [comment]
here's my `vainfo` output:
```
libva info: VA-API version 0.38.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_38
libva info: va_openDriver() returns 0
vainfo: VA-API version: 0.38 (libva 1.6.1)
vainfo: Driver version: Intel i965 driver for Intel(R) Broadwell - 1.6.1
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264MultiviewHigh      :	VAEntrypointVLD
      VAProfileH264MultiviewHigh      :	VAEntrypointEncSlice
      VAProfileH264StereoHigh         :	VAEntrypointVLD
      VAProfileH264StereoHigh         :	VAEntrypointEncSlice
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileVP8Version0_3          :	VAEntrypointVLD
      VAProfileH264MultiviewHigh      :	VAEntrypointVLD
      VAProfileH264MultiviewHigh      :	VAEntrypointEncSlice
      VAProfileH264StereoHigh         :	VAEntrypointVLD
      VAProfileH264StereoHigh         :	VAEntrypointEncSlice 
```

And yes I have `libva-intel-driver` installed.

**Comment by Ippytraxx** [comment]
I'm assuming because of the Intel chip your dedicated graphics is Nvidia. Do you have [libva-vdpau-driver](https://www.archlinux.org/packages/extra/x86_64/libva-vdpau-driver/) installed. These might be some obvious questions but as I said earlier I'm pretty sure som driver something is missing or misconfigured.

**Comment by Ippytraxx** [comment]
I just found this in the wiki page:

For hybrid setups (both NVIDIA and AMD), it may be necessary to set following environment variable:
`$ export DRI_PRIME=1`

**Comment by nashamri** [comment]
I double checked if I have some missing package. I think I have all the needed packages. I also tried `export DRI_PRIME=1` and it didn't work.
I might be doing something stupid with my configurations as I'm new to this hybrid graphics shenanigans.
I installed `vdpauinfo` to see if I can find something useful, and when I ran it I got this :smile: 
```
$ vdpauinfo 
display: :0   screen: 0
Segmentation fault (core dumped)
```

The weird thing is that it's working fine from the `master` branch.

**Comment by Ippytraxx** [comment]
That's because the master branch is using the old player that just draws directly to the X window using the CPU. This is inefficient and doesn't work on Wayland so that's why I rewrote it in Clutter, which uses the GPU to render frames.

Did you read the bit about configuration? Have you tried setting `VDPAU_DRIVER`?

Also I think that `vdpauinfo` segfaulting is a pretty strong indicator that something is definitely not configured correctly.

**Comment by nashamri** [comment]
Yeah it's looking more and like a miss-configuration issue (I'm okay with closing this issue if you see so). I've got some progress by setting `export LIBVA_DRIVER_NAME=vdpau` I'm not getting the same error and it seems it can see the  driver now but the video is still blank and now there's no sound.

This is what I get in the terminal:
```
~$ gnome-twitch 
[20:10:27] (null) - Message : '{GtApp} Activate'
libva info: VA-API version 0.38.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'vdpau'
libva info: Trying to open /usr/lib/dri/vdpau_drv_video.so
libva info: Found init function __vaDriverInit_0_35
[VS] Software VDPAU backend library initialized
libva info: VA-API version 0.38.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'vdpau'
libva info: Trying to open /usr/lib/dri/vdpau_drv_video.so
libva info: Found init function __vaDriverInit_0_35
```

Compared to what I get if I didn't set that env variable:
```
~$ gnome-twitch 
[20:15:16] (null) - Message : '{GtApp} Activate'
libva info: VA-API version 0.38.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_38
libva info: va_openDriver() returns 0

(gnome-twitch:4426): GStreamer-CRITICAL **: gst_buffer_copy_with_flags: assertion 'buffer != NULL' failed
[20:15:21] Cogl - Warning : 'driver/gl/cogl-framebuffer-gl.c:157: GL error (1280): Invalid enumeration value
```

If I get a solution, I'll report back here.

Thanks @Ippytraxx

**Comment by Ippytraxx** [comment]
Try also setting it to `va_gl` or `nvidia`. I'll leave it open for the meantime and hopefully you find a solution!

**Comment by nashamri** [comment]
I found the solution!! :smile: 
After hours of frustration, I've found it. The issue is with this package `gstreamer-vaapi`. I just removed it and the video is working fine :+1: 

It could be the same issue in #21

**Comment by Ippytraxx** [comment]
`gstreamer-vaapi` is for using the GPU as the video decoder. GStreamer will now use your CPU as the decoder which will probably cause significantly higher CPU usage. But if nothing else works then just roll with that, just letting you know.

**Comment by nashamri** [comment]
Thanks @Ippytraxx

**Comment by ceciliavision** [comment]
@nashamri  removing `gstreamer-vaapi` does save the world. Thanks a lot! I won't be able to figure that out if you didn't find it.
