### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by dengelt** [Ippytraxx/gnome-twitch#34]
I have seen that the packages at the AUR and at getdeb.net are released under the GPL-3 or later, although that information is missing in this repository.

Can you please add a LICENSE file containing the copyright notice and a GPL3 file that contains the GPL-3 license text like you did in your ZenbuTorrent repository?

Thanks!

**Comment by Ippytraxx** [comment]
Done 3814e303c97210ddd1a381ad35d445386cae58de
