### ISSUE TITLE
Improving the search functionality (Fuzzy search)

### ISSUE THREAD

**Issue by nashamri** [Ippytraxx/gnome-twitch#35]
let's say I'm looking for "The binding of isaac" game so when I click on the *Games* and click on the search button and type "isaac" it only shows a game called "Isaac the Adventurer". So I have to type "The Binding .." to find that game.

I guess maybe having a fuzzy search functionality would be a plus.

Tested on `develop`

Cheers!

**Comment by Ippytraxx** [comment]
I would like to improve on this as well but unfortunately there is nothing I can do. The games and channels searches just use Twitch's search API so it's up to them to do fuzzy matching.

If Twitch published a list of all indexed games I could do the searching locally, but they don't...
