### ISSUE TITLE
Fix need for manual post-update steps

### ISSUE THREAD

**Issue by jpakkane** [Ippytraxx/gnome-twitch#36]
Currently the readme file says that you need to do schema compilation and a few other steps manually after install. Meson has a way to do that automatically. First create a script that runs the commands like this:

    #!/bin/sh
    glib-compile-schemas /usr/share/glib-2.0/schemas
    update-desktop-database -q
    gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor

Then register it with `meson.add_install_script()`. Now Meson will run it automatically on `ninja install`.

**Comment by Ippytraxx** [comment]
Thanks for the tip! Fixed in 96136bfc7f7058e8dd47a42676923cdd2d1a7409.
