### ISSUE TITLE
Remember window height & width

### ISSUE THREAD

**Issue by jangernert** [Ippytraxx/gnome-twitch#41]
It would be really nice if upon closing gnome-twitch could write the current height and width of the window to dconf and restore the values on startup.
Right now I have to re-size the window every time gnome-twitch is started for it to fit the aspect ratio of the video.

**Comment by Ippytraxx** [comment]
On it. Also when it comes to aspect ratio, would an option that makes the video fit the screen regardless of size, be useful? I've personally been using it a bit but I don't know whether other people would.

**Comment by jangernert** [comment]
Not sure what exactly you mean.
The window will fit the aspect ratio of the video (window can only be 16:9 + headerbar), or the video will fit the aspect ratio of the window (video will be streched)?
If you are talking about the first, I'm all for it :)

**Comment by Ippytraxx** [comment]
Hmm I actually meant the latter. Both are doable so I suppose, so I'll try to add them as a option in the near future.
