### ISSUE TITLE
Remember stream quality

### ISSUE THREAD

**Issue by serianx** [Ippytraxx/gnome-twitch#43]
Hi, Can you set it to remember the stream quality you selected? Thanks for your awesome program

**Comment by Ippytraxx** [comment]
Glad you like it :)

This should already possible if you go to settings and set `Default video quality`. In GNOME it's located in the top bar, as seen here:
![settings](https://cloud.githubusercontent.com/assets/1663668/10835061/0d77ac42-7e9f-11e5-88e0-dfc317c4f7d3.png).

If this works for you then you can close the issue.

**Comment by Ippytraxx** [comment]
No reply.
