### ISSUE TITLE
Develop branch won't compile because of glib bug?

### ISSUE THREAD

**Issue by Jodell88** [Ippytraxx/gnome-twitch#46]
I'm currently trying  to compile the develop branch to test the new chat feature and seem to be running into a bug between glib and your new changes.

Error log:
(https://gist.github.com/Jodell88/769c084382452534e21f)

Link to bug on Gnome bugzilla 
(https://bugzilla.gnome.org/show_bug.cgi?id=745754)

**Comment by Ippytraxx** [comment]
Ah I just forgot to remove`gt-player-clutter.ui` from `data/gnome-twitch.gresource.xml`. I've pushed the fix now. Also you can login to Twitch and test chat (hopefully), however a lot of the stuff is not polished.

Btw you can just run `ninja clean` and then `ninja` which will force rebuilding of all resources.
