### ISSUE TITLE
Segfault happens few seconds after starting gnome-twitch (develop branch)

### ISSUE THREAD

**Issue by Jodell88** [Ippytraxx/gnome-twitch#47]
gdb points to.

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffccec3700 (LWP 15432)]
read_lines (self=0x975700) at ../src/gt-twitch-chat-client.c:199
199	        parse_line(line, msg);

**Comment by Ippytraxx** [comment]
Working on it, I'll close this issue when I think chat is _actually_ usable ( ͡° ͜ʖ ͡°).

**Comment by Ippytraxx** [comment]
Aight, I finally think chat is usable after the latest commits to master. Have at it!
