### ISSUE TITLE
Untranslatable strings in UI

### ISSUE THREAD

**Issue by piotrdrag** [Ippytraxx/gnome-twitch#54]
.desktop file is not currently translatable, as well as these strings:

https://github.com/Ippytraxx/gnome-twitch/blob/master/src/gt-game.c#L110

https://github.com/Ippytraxx/gnome-twitch/blob/master/src/gt-twitch-game.c#L110

https://github.com/Ippytraxx/gnome-twitch/blob/master/src/gt-player-clutter.c#L100

https://github.com/Ippytraxx/gnome-twitch/blob/master/src/gt-favourites-manager.c#L61

https://github.com/Ippytraxx/gnome-twitch/blob/master/src/gt-favourites-manager.c#L62

https://github.com/Ippytraxx/gnome-twitch/blob/master/src/gt-channels-container-child.c#L100

https://github.com/Ippytraxx/gnome-twitch/blob/master/src/gt-channels-container-child.c#L127

https://github.com/Ippytraxx/gnome-twitch/blob/master/src/gt-channels-container-child.c#L129

They should be marked for translation, if they are shown to the user.

**Comment by Ippytraxx** [comment]
Yeah, I'll clean this up for 0.2.0 when I have to add a whole bunch of new strings anyways.

**Comment by ricbermo** [comment]
hey, how can I contribute?, I can speak Spanish and French

**Comment by Ippytraxx** [comment]
@ricbermo Awesome! Currently @hmsintrepide is handling the French translation but there is no spanish translation so that would be great. You can check out the https://github.com/Ippytraxx/gnome-twitch/blob/master/CONTRIBUTING.md on how to set up a pot file to translate. However I will soon try to release 0.2.0 which will have a lot of new stuff to translate, so it's probably best to wait until then because anything translated now won't be available until 0.2.0 anyways.

**Comment by ricbermo** [comment]
@Ippytraxx thank you. I'll try configure this tonight in order to the the PO file. Tomorrow during my lunch time (I'm currently working) I'll translate that. BTW, any system requirements needed besides gnome-shell?

**Comment by Ippytraxx** [comment]
All dependencies are listed in the readme, but if you have gnome-shell then most of them should already be installed.

**Comment by ricbermo** [comment]
@Ippytraxx I already finished this. I successfully installed the software but it does not start. Can I submit the PR w/o testing? btw. I added Spanish translations for both Latin America and Spain. It'd be nice someone from Spain review it.

**Comment by Ippytraxx** [comment]
Nice work! It's fine if you can't test it, I'll test it anyways before I merge the PR. But you can probably wait until 0.2.0 till you submit a pull request as there will be more stuff to translate. I'll ping all translators on GH when that happens.

**Comment by ricbermo** [comment]
Ok. I'll be waiting for you email. Thank you

**Comment by ricbermo** [comment]
@Ippytraxx you a noob question here. how can I uninstall the program?

**Comment by Ippytraxx** [comment]
Unfortunately Meson offers no easy way to uninstall unlike autotools does. You'll have to manually remove `/usr/bin/gnome-twitch, /usr/share/icons/hicolor/*/apps/gnome-twitch.{png,svg}, /usr/share/locale/*/LC_MESSAGES/gnome-twitch.mo, /usr/share/applications/com.gnome-twitch.app.desktop, /usr/share/glib-2.9/schemas/gnome-twitch.gschema.xml`

After that you need to recompile your glib schemas and if you want to do a complete wipe then you can also delete any GNOME Twitch settings using dconf.
