### ISSUE TITLE
can not connect to a channel

### ISSUE THREAD

**Issue by legluondunet** [Ippytraxx/gnome-twitch#59]
Hello, I don't understand why I can not see the http://www.twitch.tv/gamingonlinux channel with gnome-twitch.

I type gamingonlinux in the search field and nothing appear.

Thank you for your help.

LGDN

**Comment by Ippytraxx** [comment]
Is th channel offline? You can currently only search online channels. I plan on adding searching for offline channels soon.

**Comment by legluondunet** [comment]
If I type "gamingonlinux" in the serach field  it should find the channel during live, isnt it?
I will try next week and tell you if it  works.
Could you try too next friday at 18h00?

**Comment by Ippytraxx** [comment]
You were actually right, apparently the hls=true doesn't do what it's supposed to do.

**Comment by legluondunet** [comment]
I will try to compile the last git to try

**Comment by legluondunet** [comment]
I just compiled the last development branch.
I will try it next Friday with the same channel.

Regards.

**Comment by legluondunet** [comment]
Work like a charm, thank you.
