### ISSUE TITLE
Settings schema is not installed.

### ISSUE THREAD

**Issue by codemusings** [Ippytraxx/gnome-twitch#6]
I've compiled the app on Debian Sid. Got the following error:

```bash
(gnome-twitch:9130): GLib-GIO-ERROR **: Settings schema 'com.gnome-twitch.app' is not installed
```

Should a post install step be added that recompiles the glib schema files? I had to do that by hand to get the app running.

**Comment by Ippytraxx** [comment]
This is something I believe the package manager should do. Checkout the .install file I have for Arch.
I'll add this to the readme about installing.

**Comment by codemusings** [comment]
Yeah I guess it's too distro specific to add this to the build configuration.
