### ISSUE TITLE
compile error on Ubuntu 15.10

### ISSUE THREAD

**Issue by legluondunet** [Ippytraxx/gnome-twitch#64]
Hello,

I just downloaded the last develop git branche. 
When I try to compile it, I obtain this error message:

$ meson --prefix /usr -Ddo-post-install=true ..
The Meson build system
Version: 0.21.0
Source dir: /home/legluondunet/Applications_persos/Multimedia/gnome-twitch/gnome-twitch-develop
Build dir: /home/legluondunet/Applications_persos/Multimedia/gnome-twitch/gnome-twitch-develop/build
Build type: native build

Meson encountered an error in file meson.build, line 4, column 32:
lexer

Thank you for your help.

**Comment by jhaye** [comment]
You need *meson* >= 0.26.0 to build this from source successfully.

**Comment by legluondunet** [comment]
meson>=2.6 is not available for Ubuntu Wily 15.10 and needs ninja 1.5.1.
But I found a workaround:
I downloaded the the Ubuntu Xenial 16.04 version here:
https://launchpad.net/ubuntu/xenial/amd64/meson/0.28.0-2
https://launchpad.net/ubuntu/xenial/amd64/ninja-build/1.5.1-0.1ubuntu1

Then I installed this dependencies packages:

$ sudo apt-get install libgtk-3-dev libclutter-gst-3.0-dev libclutter-gtk-1.0-dev libwebkit2gtk-4.0-dev

After this steps I compiled and installed it with success:
$ mkdir build
$ cd build
$ meson --prefix /usr -Ddo-post-install=true ..
$ sudo ninja install

and the new gnome-twich version launches normally.

Now could you say me how:
- to clean the compiled folder, is there a meson/ninja make clean equivalent?
- uninstall gnome-twitch, sudo ninja uninstall does not work

Once again thank you for your help.

**Comment by Ippytraxx** [comment]
There is `ninja clean` however there is no uninstall option. You will either have to remove the files manually. I pretty much desribed the process in another issue:

You'll have to manually remove `/usr/bin/gnome-twitch, /usr/share/icons/hicolor/*/apps/gnome-twitch.{png,svg}, /usr/share/locale/*/LC_MESSAGES/gnome-twitch.mo, /usr/share/applications/com.gnome-twitch.app.desktop, /usr/share/glib-2.0/schemas/gnome-twitch.gschema.xml`

After that you need to recompile your glib schemas and if you want to do a complete wipe then you can also delete any GNOME Twitch settings using dconf.

**Comment by legluondunet** [comment]
To install/uninstall it I finally used checkinstall to make a deb paquet.

$ sudo checkinstall ninja install

Like this I could uninstall properly gnome-twich.

thank you to take the time to answer.
