### ISSUE TITLE
Hide log in to Twitch

### ISSUE THREAD

**Issue by bil-elmoussaoui** [Ippytraxx/gnome-twitch#65]
When i'm connected to my account, log in to twitch should be changed to logout or something else :+1:

**Comment by Ippytraxx** [comment]
Even if it says log in a notification bar should come up saying if you want to refresh your login i.e. your oauth token. But I agree that it can be a bit confusing so I've changed this to "Refresh login" when you are actually logged in. There really isn't any concept of "logging out" per-se so I think this is the next best option.
