### ISSUE TITLE
No package for Fedora 23

### ISSUE THREAD

**Issue by Algram** [Ippytraxx/gnome-twitch#66]
In the COPR are only packages for Fedora 22 and Fedora Rawhide (24). This means enabling the repo on Fedora 23 works but it wont find the package there, hence you cant use Gnome Twitch on Fedora 23.

**Comment by Ippytraxx** [comment]
Sure once 0.2.0 is done I'll be on it.

**Comment by martinoj2009** [comment]
I moved over to Fedora 23 and was also disappointed I don't have a package for 23. Would like to see one for 23 and soon 24.

**Comment by Romelhun** [comment]
I faced with same issue. 

**As workaround until fixing this issue download and install the rpm directly:**

[https://copr-be.cloud.fedoraproject.org/results/ippytraxx/gnome-twitch/fedora-22-x86_64/00129309-gnome-twitch/gnome-twitch-0.1.0-2.fc22.x86_64.rpm](https://copr-be.cloud.fedoraproject.org/results/ippytraxx/gnome-twitch/fedora-22-x86_64/00129309-gnome-twitch/gnome-twitch-0.1.0-2.fc22.x86_64.rpm)

**Comment by Corsseir** [comment]
Iam also waiting on Fedora 23 version of this great software.

**Comment by Ippytraxx** [comment]
Actually it seems like copr has added automated package building from a git repo (just like the AUR)!! So I'll see if I can get a git package rolling during the weekend so you guys at least have something until 0.2.0.

**Comment by rfajfar** [comment]
Its not hard to install from source...

**Comment by Algram** [comment]
@rfajfar It is for a lot of people. So making the install process of software as easy as possible is important. Not to mention the automatic updating, etc.

**Comment by Ippytraxx** [comment]
Well building from git didn't work as planned... But there are now 0.2.0 packages available for Fedora 23, 24 and Rawhide! Unfortunately 22 doesn't have a high enough version of meson and I don't feel like maintaining the autotools version anymore.

I'll try to keep on top of packages from now on.
