### ISSUE TITLE
Chat scrolls back down to new messages when the user has scrolled up

### ISSUE THREAD

**Issue by dengelt** [Ippytraxx/gnome-twitch#68]
Currently, whenever a new message arrives, the chat window automatically scrolls down to the latest message, even when the scrollbar is not at the very bottom. This makes it hard to read older messages or copy links, especially when the chat is moving fast. In most chat applications, when the user scrolls up to read older messages, new messages will not cause the chat window to scroll back down. Instead the scrollbar will remain where it is until the user scrolls to the bottom of the chat window. I believe this should also be the intended behavior for gnome-twitch, too.

**Comment by Ippytraxx** [comment]
Yes this is indeed the intended behaviour. I just need to code the functionality so that when the user scrolls up it doesn't "stick" to the bottom until the user scrolls down again.
