### ISSUE TITLE
Needs a newer version of Meson?

### ISSUE THREAD

**Issue by hadess** [Ippytraxx/gnome-twitch#7]
```
$ meson . build
The Meson build system
Version: 0.25.0
Source dir: /home/hadess/Projects/jhbuild/gnome-twitch
Build dir: /home/hadess/Projects/jhbuild/gnome-twitch/build
Build type: native build

Meson encountered an error in file meson.build, line 1, column 0:
project() only accepts the keyword argument "subproject_dir"
```

**Comment by Ippytraxx** [comment]
Yes 0.26.0 for the 'version' argument in the project command. You can use the master-autotools branch if you are having trouble with Meson.

**Comment by hadess** [comment]
> Yes 0.26.0 for the 'version' argument in the project command.

Mind adding the requirement to the README?

> You can use the master-autotools branch if you are having trouble with Meson.

It should have an autogen.sh file, but that works for me.

**Comment by Ippytraxx** [comment]
Done ed7e2686681e8ec6a2a08bafb2c9d126d6a2b0fc
