### ISSUE TITLE
segfault and chat settings not saved

### ISSUE THREAD

**Issue by ert65** [Ippytraxx/gnome-twitch#71]
I am using gnome-twitch-git from aur and every time when try to change the stream after watching one, the program closed with segfault. Also when i make changes to chat settings, like position or unmark "dock chat", next time when i open the program, those settings are default.

**Comment by Ippytraxx** [comment]
I can't seem to replicate the segfaults you are getting, can you provide any more info? 

As for the settings, I am currently working on per-stream settings for chat so you won't have to set them every time. Just remember the git package is almost like a "preview" of things to come so a lot of times there will be bugs and incomplete features, but thanks for asking!

**Comment by ert65** [comment]
According to #30, my issue is with gstreamer-vaapi. Without it, now the app works as expected. I am using lap top with hybrid graphic (optimus). Now it uses cpu, but its working. Thank you for your answer and i hope someday, that the app will work without problems with gstreamer-vaapi and reduce the cpu usage.

**Comment by Ippytraxx** [comment]
Yeah, unfortunately vaapi doesn't play well with hybrid graphics. Luckily I have a laptop with hybrid graphics so I might be able to do some trouble shooting in the future.

**Comment by Ippytraxx** [comment]
Chat settings are now saved.
