### ISSUE TITLE
Post install script assumes `--prefix=/usr`

### ISSUE THREAD

**Issue by mattiasb** [Ippytraxx/gnome-twitch#86]
I would assume `meson_post_install.sh` to take the prefix value in to account. Currently it is hardcoded to `/usr/` making user installations fail.

**Comment by Ippytraxx** [comment]
Hmmm, I'll see if I can do something with meson to pass the prefix to the shell script.

**Comment by Ippytraxx** [comment]
Fixed by @dchristidis in #94
