### ISSUE TITLE
Translations for 0.2.0

### ISSUE THREAD

**Issue by Ippytraxx** [Ippytraxx/gnome-twitch#92]
@pfent @hmsintrepide @piotrdrag @Generator @kostich 

So 0.2.0 is finally here and in need of new translations. I've gone through the code and marked as many translatable strings as I can find however if you find any unmarked ones please let me know. 

Please use commit 66a867df9f37761f49522d14f427f6c4d623a88a as the base (unless more strings are found) for your translations and commit them into master.

New pot templates can be generated by going to the `build` directory and running `ninja pot` which wille create `gnome-twitch.pot` in the `po` directory.

I would be grateful if you could complete them as soon as possible so I can get get 0.2.0 out the door (been delayed way too long already). Remember to fill out the metadata at the top of the po file ;)

Thanks in advance!

**Comment by kostich** [comment]
Sure thing buddy. Will complete this tonight (20:00 +0200).

**Comment by hmsintrepide** [comment]
Ok, I did a pull request with a spelling correction.

2016-04-04 7:47 GMT+02:00 kostich <notifications@github.com>:

**Comment by Ippytraxx** [comment]
@riflex Sorry couldn't find your account before, are you able to update your translation?

**Comment by riflex** [comment]
Sure, will be done in the following 1-2 days.

**Comment by Ippytraxx** [comment]
Ok nice. @kostich if you can complete yours as well, then I can release 0.2.0 during the weekend.

**Comment by kostich** [comment]
@Ippytraxx, done! Also, it seems that Portuguese translator didn't credit himself properly (he translated literally "translator-credits" string instead of writting "Name Surname <email@address>">. Maybe create a comment for that string so people don't get confused?

**Comment by Ippytraxx** [comment]
Yeah that's probably a good idea.

**Comment by Generator** [comment]
@kostich you are right, i was thinking that was a header for the list of translators.

**Comment by piotrdrag** [comment]
BTW the correct language code for Portuguese in GNOME is "pt", so the file should be named "pt.po".

**Comment by dengelt** [comment]
In this case yes, since Portuguese as spoken in Portugal (pt_PT) is the language’s main dialect, and according to the [GNU gettext documentation](https://www.gnu.org/software/gettext/manual/gettext.html#Header-Entry) (Paragraph "Language" at section 6.2) the country code should be omitted for the language’s main dialect. This is independent of GNOME though.

**Comment by Ippytraxx** [comment]
@pfent @hmsintrepide @piotrdrag @Generator @kostich @Sunderland93 @kostich @riflex 

Thank you very much guys for your help! I think I'll ping for translations at 0.x releases (minor) and skip translations for 0.0.x releases (patch). 0.2.0 should be out in the next day or two.
